# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=200)),
                ('bid_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('seller', models.CharField(default=b'', max_length=200)),
                ('date_added', models.DateTimeField()),
                ('image', models.ImageField(default=b'/home/hypatia/Downloads/thumbnail-default.jpg', upload_to=b'/home/hypatia/bidengine/image')),
                ('status', models.CharField(default=b'Available', max_length=20)),
                ('min_bid', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items'),
        ),
    ]
